version: '3.8'

networks:
  photogram_container:

services:
  &db db:
    image: postgres:16
    restart: always
    hostname: postgres
    env_file:
      - '.env'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_photogram_container:/var/lib/postgresql
    networks:
      - photogram_container

volumes:
  postgres_data_photogram_container: